### ISSUE TITLE
Create more informative home page

### ISSUE THREAD

**Issue by michaelwm** [uwreact/shire#1]
# 📚 Meta Issue

The home page is currently at a minimum for providing information about the team. There is a lot more information available about the team that will help ease on-boarding for those interested in joining the team and anyone just looking to learn more about our mission.

### Tracking

- [ ] Add sponsors section with all [old sponsors](https://web.archive.org/web/20180126170312/https://uwri3d.com/#sponsors), sponsor form and sponsor email. #2
- [ ] Add contact form and contact email. #3
- [ ] Add social media links. #4
- [ ] Add photos from UWRi3D 2018. #5
- [ ] Rewrite and add much more information about FIRST, FRC, and autonomous FRC. #6
- [ ] Add countdown to kick off. #7
