### ISSUE TITLE
Set up basic CI infrastructure

### ISSUE THREAD

**Issue by michaelwm** [uwreact/shire#13]
# 📚 Meta Issue

There is currently no continuous integration server running for shire, making updating the website more difficult. [Buildkite](http://buildkite.com) was to be used, but does require a number of configuration steps and would ultimately take too much time for the simple configuration we need. [Travis](https://travis-ci.org) provides everything we need, since we are completely open source, and is very quick to set up. If we ever need more customization, especially for our other projects, the infrastructure team can move to [Jenkins](https://jenkins.io/) as a larger project. For now, Travis will work.

## Tracking

- [ ] Set up and add `.travis.yml` for basic master branch updates. #14 
- [ ] Add staging branch and add to `.travis.yml`. #15 
- [ ] Add testing for all branches as checks for PR's. #16
