### ISSUE TITLE
Create UW Ri3D home page

### ISSUE THREAD

**Issue by michaelwm** [uwreact/shire#8]
# 📚 Meta Issue

[uwri3d.com](https://uwri3d.com) and [uwri3d.ca](https://uwri3d.ca) now point to [uwreact.ca/ri3d](https://uwreact.ca/ri3d) since we have consolidated the two initiatives. The UW Ri3D home page is currently a 404, but it should appear similar to the UW REACT home page. It should contain most of the information present on the [old site](https://web.archive.org/web/20180126170312/https://uwri3d.com/), but with additional information based on it's new role in the UW REACT organization.

## Tracking

- [x] Add all information from old website, reusing UW REACT homepage material where possible. #9 
- [x] Create links to and from UW REACT homepage. #10 
- [x] Add information about UW Ri3D applications. #11
